// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDYzmOfXgHVsxZheKjxXh8AkvTG5wtts',
    appId: '1:609734281684:web:e8ab6d5cecdf972adbee41',
    messagingSenderId: '609734281684',
    projectId: 'device-streaming-3706235e',
    authDomain: 'device-streaming-3706235e.firebaseapp.com',
    storageBucket: 'device-streaming-3706235e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxBRMBkDkbuir0MT9UJz8pRoDrQuIDBc',
    appId: '1:609734281684:android:e8a09baf8a2afd6adbee41',
    messagingSenderId: '609734281684',
    projectId: 'device-streaming-3706235e',
    storageBucket: 'device-streaming-3706235e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4w8fNjQXwctXeu7yh0IIbLUmZ3cRj7kQ',
    appId: '1:609734281684:ios:c205cb087565b379dbee41',
    messagingSenderId: '609734281684',
    projectId: 'device-streaming-3706235e',
    storageBucket: 'device-streaming-3706235e.firebasestorage.app',
    iosBundleId: 'com.example.humoOnline',
  );
}
